global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Scheduled-DB cluster monitoring
  - job_name: 'scheduled-db'
    static_configs:
      - targets:
          - 'scheduled-db-1:8080'
          - 'scheduled-db-2:8080'
          - 'scheduled-db-3:8080'
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http
    honor_labels: false
    honor_timestamps: true
    params:
      format: ['prometheus']

  # Nginx load balancer monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s
    scrape_timeout: 5s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Container metrics (if cAdvisor is available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: false
    params:
      collect[]:
        - 'container_cpu_usage_seconds_total'
        - 'container_memory_usage_bytes'
        - 'container_network_receive_bytes_total'
        - 'container_network_transmit_bytes_total'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 15d
    retention.size: 10GB
    wal-compression: true

# Web configuration
web:
  console.libraries: /etc/prometheus/console_libraries
  console.templates: /etc/prometheus/consoles
  enable-lifecycle: true
  enable-admin-api: true
