apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: scheduled-db-pdb
  namespace: default
  labels:
    app: scheduled-db
    component: pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: scheduled-db
