apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduled-db
  namespace: default
  labels:
    app: scheduled-db
    component: rbac
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduled-db
  labels:
    app: scheduled-db
    component: rbac
rules:
# Read pods for service discovery
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update", "patch"]
# Read services for discovery
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
# Read endpoints for service discovery
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
# Read nodes for cluster information
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduled-db
  labels:
    app: scheduled-db
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scheduled-db
subjects:
- kind: ServiceAccount
  name: scheduled-db
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scheduled-db
  namespace: default
  labels:
    app: scheduled-db
    component: rbac
rules:
# Access to ConfigMaps in same namespace
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Access to Secrets in same namespace (if needed for TLS)
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scheduled-db
  namespace: default
  labels:
    app: scheduled-db
    component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scheduled-db
subjects:
- kind: ServiceAccount
  name: scheduled-db
  namespace: default
